EXTENDS base
TITLE Caderno de Historia
TAGS notes school

# história

# Exploração colonial das Américas - Espanha

## O império dos metais

Alguns fatos sobre a exploração colonial na América espanhola:

- Em 1521, conquistam o Império Asteca
- Em 1533, conquistam o Império Inca
- Causaram morte sem precedentes de nativos, por meio de guerras e doenças. No início do século XVI (~1500), a população era de cerca de 25 milhões. Em 1605, era 1 milhão.

Fatores que causavam a morte dos nativos:

- Guerras
- Doenças
- Trabalho nas minas:
  - Ouro - na atual Colômbia
  - Prata - México, Bolívia

## Controle da exploração

O controle da exploração era exercido por três grupos de pessoas:

**Adilantados** - amigos do rei que migravam para América em troca do controle de terras. Eram governadores com poder de justiça.

**Encomienda** - responsável pelo controle da mão de obra nativa. Encomendeiros:

- Não recebiam terras
- Estimulavam evangelização dos nativos
- Tinham que pagar imposto real (quinto - 1/5 dos metais retirados deveriam ser pagos ao rei)

**Repartimiento** - funcionários reais que migram para a América para controlar a exploração.

- Controla a mão de obra nativa
- Deveriam pagar salário aos índios
- Evangelizavam os nativos

## Sociedade

Pirâmide Social, de baixo para cima:

**Nativos** - Nativos das regiões exploradas

**Escravos** - Negros, em pequena quantidade

**Mestiços** - Filhos de espanhóis com indígenas. Correspondiam a classe média (artesãos, comerciantes etc.)

**Criollos** - Espanhois nascidos na América. Tinham que ter ambos os pais de espanhois. Eram grandes proprietários de terra. Se sentiam discriminados por não poderem assumir a posição de chapetones.

**Clero** - Membros da Igreja

**Chapetones** - Espanhois possuídores das principais funções administrativas e jurídicas.

## Controle e Monopólio

**Regime do Porto Único** - Apenas um porto em toda a Espanha receberia todas as riquezas provindas de suas colônias na América. (Inicialmente era o Porto de Sevilha e depois o Porto de Cádiz)

Buscava maior controle sobre as riquezas e diminuir o  contrabando.

As riquezas eram enviadas a partir de três portos na América:

- Vera Cruz - México
- Cartagena - Colômbia
- Porto Belo - Panamá

# Exploração colonial das Américas - Portugal

## Pela riqueza do rei

Nas colônias portuguesas na América, existiam entrepostos comerciais, chamados:
**Feitorias** - Praça comercial militarizada. Funcionavam também como mercado, armazém, alfândega, ponto de defesa e de apoio a navegação. Nelas eram também comercializados escravos e especiarias.

## Importância do Brasil

O período pré-colonial (1500-1532) marca o espaço de tempo entre o descobrimento do Brasil e o início de sua colonização.

**1ª Expedição** - Em 1532, Martim Afonso de Souza comandou a primeira expedição no Brasil, marcando assim o fim do período pré-colonial.

Nessa época, o Brasil tinha duas atividades econômicas princípais:
**1ª atividade econõmica** - A extração do **Pau Brasil**, que tinha em seu tronco um pigmento usado na fabricação de tintas vermelhas.

**2ª atividade econômica** - **Açúcar**. Os portugueses tinham como motivos para a fabricação do açúcar:

- A elevada **procura** pelo produto na Europa
- A **experiência anterior** que tinham com sua produção.

## Escravos

Inicialmente, os portugueses fizeram uso da **mão de obra nativa** para a escravidão. Mas com isso se depararam com alguns problemas:

- **Fuga** - Muitos nativos fugiam para evitar a escravização.
- **Doenças**-  Os nativos eram muito mais suscetíveis às doenças trazidas da Europa.
- **Jesuítas** - Os jesuítas defendiam que os nativos não deveriam ser escravizados.

Os portugueses decidiram então buscar a **mão de obra africana**. Assim, passaram a ser vendidos prisioneiros de guerra africanos nas feitorias, por meio do escambo (troca de produtos).

**Escambo** - Algumas das coisas pelas quais poderiam ser trocados escravos eram:

- Armamento
- Cavalo (valia 10 escravos)
- Aguardente
- Munição

Assim, foram na época trazidos 12 milhões de escravos africanos para as américas, sendo:

- 6 milhões para o Brasil
- 5 milhões para o Caribe
- 600.000 para o sul dos Estados Unidos

# Exploração colonial das Américas - Inglaterra

## Colônias Inglesas - Destaques

A rainha da Inglaterra era Elizabeth I.

**Colônia da Virgínia** - primeira colônia inglesa na América

**James I** - rei inglês que impulsionou a colonização inglesa na América.

Em 1607 é fundada a cidade de **Jamestown** na Virgínia.

Em 1620, vieram os **Peregrinos Mayflower**. Um grupo de 102 viajantes que se fixou Massachussets. Sofreram muito com a falta de comida, mas com o dia da colheita se iniciou a tradição do dia de ação de graças.

Estavam ocorrendo as guerras Anglo-Holandesas. Assim, os ingleses trocaram o nome de Nova Amsterdã fundada pelos holandeses para **Nova York**.

William Penn recebeu o controle da **Pensilvânia** e sendo um Quaker (perseguido na Inglaterra), declarou que o estado teria liberdade religiosa, fazendo com que muitos Quakers da Inglaterra se mudassem para lá.

## Autonomia e diversidade

Algumas característcas básicas dos três grupos de colônias nos Estados Unidos e alguns dos produtos que produziam:

Colônias do **Norte:**

- Região conhecida como Nova Inglaterra
- Eram puritanos
- Construção de Navios
- Comércio Marítimo
- Pesca de baleias
- Rum - Produzido no caribe

Colônias do **Centro**:

- Eram conhecidas também como "Colônias do Pão"
- Eram Protestantes
- Centeio
- Cevada
- Milho
- Trigo
- Pecuária

Colônias do **Sul**

- Eram católicos
- Onde se concentrou a maior parte da mão de obra negra
- Arroz
- Tabaco
- Algodão

## Mecantilismo

O Mercantilismo é a política econômica utilizada pelas monarquias absolutistas para controlar suas colônias.

# Colonização da América portuguesa

## Período pré-colonial

O período pré-colonial é o período que começou com o descobrimento do Brasil em 1500 e terminou com o ínicio de sua colonização, marcado pela primeira expedição em 1532. 

Como vimos anteriormente, a principal atividade econômica era a exploração do Pau-Brasil. Ocorria o escambo nas feitorias.

Em 1532, ocorreu a **1ª expedição** com Martin Afonso de Sousa.
Ela tinha como objetivos:

- Tomar a posse do território, que estava sendo ameaçada por outros países como a França
- Explorar as terras
- Combater os franceses
- Fundar núcleos populacionais, sendo o primeiro São Vicente
- Trazer para o Brasil as primeiras mudas de cana de açúcar. (Já tinham experiência com o produto, ele tinha alto valor na Europa e o  clima e solo eram ideais)

## Estrutura Político Administratitva

**Ordenações Manuelinas** - Leis que buscavam adequar a administração do Reino de Portugal para sua enorme expansão devida aos descobrimentos.

**Dom João** - Estabeleceu como prioridades para o desenvolvimento do Brasil:

- A criação de fortalezas
- O combate aos mouros (Como eram chamados os muçulmanos na península ibérica)
- Colonização do Brasil
- A divisão do país em diversas capitanias hereditárias.

### **Capitanias Hereditárias**

O Brasil foi divido em 15 regiões que tinham como objetivo a exploração econômica da colônia sem o uso de recursos do Estado (que não tinha recursos o suficiente para a colonização).

**Donatário** - Título dado ao nobre que possuísse uma capitania hereditária. Recebia dois documentos:

- **Carta de Doação**: descreve direitos e deveres do nobre como Donatário.
- **Foral**: Documento Complementar

**Direitos do donatário**

- Aplicação da justiça
- Doação de sesmarias = latifúndios (grandes pedaços de terra)
- Explorar a terra

**Deveres do donatário**

- Povoar as capitanias hereditárias
- Cobrar impostos

As capitanias hereditárias **falharam**, pois:

- Havia falta de recursos
- Grande distância entre colônia e metrópole
- Ataques dos nativos
- Densa vegetação

Foi assim criado o **governo geral**.

## Governo Geral

O governo geral centralizava a administração da colônia, buscando assim melhor ajudar os donatários e combater os franceses.

**1º Governador Geral** - Tomé de Souza (1549-1553)

Tinha entre seus deveres:

- Garantir a segurança da colônia
- Distribuir sesmarias
- Realizar a justiça
- Povoar a colônia
- Cobrar impostos
- Catequizar nativos<Paste>
